# Generated by Django 4.1.4 on 2023-02-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='age',
            field=models.IntegerField(default=19),
        ),
        migrations.AddField(
            model_name='register',
            name='catalogue',
            field=models.CharField(choices=[('p', 'PRESENT'), ('E', 'EX'), ('O', 'OTHERS')], default='p', max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
