# Generated by Django 4.1.4 on 2023-02-25 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_log_rename_register_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
