# Generated by Django 4.1.4 on 2023-02-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='password',
            new_name='password2',
        ),
        migrations.AddField(
            model_name='registration',
            name='password1',
            field=models.CharField(default='null', max_length=30),
        ),
    ]
