# Generated by Django 4.1.4 on 2023-02-25 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_password_registration_password2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('O', 'OTHERS')], max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='password1',
            field=models.CharField(default='', max_length=30),
        ),
    ]
